baseURL = "http://example.org/"
languageCode = "en-us"
title = "Big 5 RPG"
theme = "hugo-theme-massively"


[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]

[languages]
[languages.en]
  languageName = "English"
[languages.es]
  languageName = "Español"